name: Build Elun Demo GBA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Grab your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Bring up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # 3) Install the GB Studio CLI (correct package name)
      - name: Install GB Studio CLI
        run: npm install -g gb-studio-cli

      # 4) Build the GBA ROM
      - name: Build GBA ROM
        run: |
          mkdir -p demos
          npx gb-studio-cli build project.json \
            --target gba \
            --out demos/Elun_Demo_v1.0.gba

      # 5) Zip it up
      - name: Zip ROM
        run: |
          mkdir -p release
          zip -j release/Elun_Demo_v1.0.zip demos/Elun_Demo_v1.0.gba

      # 6) Create a GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0-demo
          name: Elun Demo v1.0
          body: |
            **Elun Demo v1.0**  
            • Built via CI  
            • Passwords: RUNE9, RUPDOG, GMONEY, GOOSE / GDEVEL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7) Upload the ZIP as the release asset
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          artifacts: release/Elun_Demo_v1.0.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}