name: Build Elun Demo GBA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install GB Studio CLI
        run: npm install -g @gbstudio/cli@3

      - name: Build GBA ROM
        run: |
          mkdir -p demos
          gbstudio-cli build project.json \
            --target gba \
            --out demos/Elun_Demo_v1.0.gba

      - name: Zip ROM
        run: |
          mkdir -p release
          zip -j release/Elun_Demo_v1.0.zip demos/Elun_Demo_v1.0.gba

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0-demo
          name: Elun Demo v1.0
          body: |
            **Elun Demo v1.0**  
            – Built via CI  
            – Passwords: RUNE9, RUPDOG, GMONEY, GOOSE / GDEVEL  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          artifacts: release/Elun_Demo_v1.0.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
